#!/bin/bash

TEST_FILENAME=3737.xml
TEST_DIR="/mnt/pressgang/TOPICS/00000 - 09999/3000 - 3999/3700 - 3799/3730 - 3739/3737"
TEST_DOC=${TEST_DIR}/${TEST_FILENAME}
TEMP_DIR=/tmp
TEMP_DOC=${TEMP_DIR}/${TEST_FILENAME}
DOCBOOK_HTML_XSL=/usr/share/sgml/docbook/xsl-stylesheets-1.75.2/html/docbook.xsl
DOCBOOK_DTD=/usr/share/sgml/docbook/xml-dtd-4.5-1.0-51.el6/docbookx.dtd
JING_JAR=/home/mcaspers/Applications/jing-20091111/bin/jing.jar

#sudo mount.davfs http://skynet-dev.usersys.redhat.com:8080/pressgang-ccms-webdav /mnt/pressgang -o uid=matthew

# cp test 1
echo Starting cp test 1
cp "${TEST_DOC}" "${TEMP_DIR}"
diff "${TEST_DOC}" "${TEMP_DOC}"

if [[ $? -ne 0 ]]
then
	echo "************ cp test 1 failed ************"
fi

# cp test 2
echo Starting cp test 2
echo '<!-- cp test 2 -->' > "${TEMP_DOC}"
cp "${TEMP_DOC}" "${TEST_DIR}"
diff "${TEST_DOC}" "${TEMP_DOC}"

if [[ $? -ne 0 ]]
then
	echo "************ cp test 2 failed ************"
fi

# cat test 2
echo Starting cat test 1
echo '<!-- cat test 1 -->' > "${TEMP_DOC}"
echo '<!-- cat test 1 -->' > "${TEST_DOC}"
cat "${TEMP_DOC}" > /tmp/cattest1
cat "${TEST_DOC}" > /tmp/cattest2
diff /tmp/cattest1 /tmp/cattest2

if [[ $? -ne 0 ]]
then
	echo "************ cat test 1 failed ************"
fi

# redirect test 1
echo Starting redirect test 1
echo '<!-- redirect test 1 -->' > "${TEMP_DOC}"
echo '<!-- redirect test 1 -->' > "${TEST_DOC}"
diff "${TEST_DOC}" "${TEMP_DOC}"

if [[ $? -ne 0 ]]
then
	echo "************ redirect test 1 failed ************"
fi

# grep test 1
echo Starting grep test 1
echo -e "I love grep\ngrep is the best" > "${TEMP_DOC}"
echo -e "I love grep\ngrep is the best" > "${TEST_DOC}"
grep grep "${TEMP_DOC}" > /tmp/grep1.tmp
grep grep "${TEST_DOC}" > /tmp/grep2.tmp

diff /tmp/grep1.tmp /tmp/grep2.tmp

if [[ $? -ne 0 ]]
then
	echo "************ grep test 1 failed ************"
fi

# xmllint test 1
echo Starting xmllint test 1
echo '<section></section1>' > "${TEMP_DOC}"
echo '<section></section1>' > "${TEST_DOC}"
xmllint --valid "${TEMP_DOC}" 2> /tmp/xml1.tmp
xmllint --valid "${TEST_DOC}" 2> /tmp/xml2.tmp

sed -e 's/${TEMP_DOC}//g' /tmp/xml1.tmp > /tmp/xml1.tmp
sed -e 's/${TEST_DOC}//g' /tmp/xml2.tmp > /tmp/xml2.tmp

diff /tmp/xml1.tmp /tmp/xml2.tmp

if [[ $? -ne 0 ]]
then
	echo "************ xmllint test 1 failed ************"
fi

# xmllint test 2
echo Starting xmllint test 2
echo '<section></section>' > "${TEMP_DOC}"
echo '<section></section>' > "${TEST_DOC}"
xmllint --output "${TEMP_DOC}" "${TEMP_DOC}"
xmllint --output "${TEST_DOC}" "${TEST_DOC}"

diff "${TEST_DOC}" "${TEMP_DOC}"

if [[ $? -ne 0 ]]
then
	echo "************ xmllint test 2 failed ************"
fi

# sed test 1
echo Starting sed test 1
echo '<!-- sed test -->' > "${TEMP_DOC}"
echo '<!-- sed test -->' > "${TEST_DOC}"
sed 's/test/sedreplaced/g' "${TEMP_DOC}" > "${TEMP_DOC}"
sed 's/test/sedreplaced/g' "${TEST_DOC}" > "${TEST_DOC}"
diff "${TEST_DOC}" "${TEMP_DOC}"

if [[ $? -ne 0 ]]
then
	echo "************ sed test 1 failed ************"
fi

# saxon test 1
echo Starting saxon test 1
echo '<article><title>test</title><para>hi</para></article>' > "${TEMP_DOC}"
echo '<article><title>test</title><para>hi</para></article>' > "${TEST_DOC}"
saxon -o /tmp/docbook1.html "${TEMP_DOC}" "${DOCBOOK_HTML_XSL}"
saxon -o /tmp/docbook2.html "${TEST_DOC}" "${DOCBOOK_HTML_XSL}"
diff /tmp/docbook1.html /tmp/docbook2.html

if [[ $? -ne 0 ]]
then
	echo "************ saxon test 1 failed ************"
fi

# xsltproc test 1
echo Starting xsltproc test 1
echo '<article><title>test</title><para>hi</para></article>' > "${TEMP_DOC}"
echo '<article><title>test</title><para>hi</para></article>' > "${TEST_DOC}"
xsltproc -o /tmp/docbook1.html "${DOCBOOK_HTML_XSL}" "${TEMP_DOC}" 
xsltproc -o /tmp/docbook2.html "${DOCBOOK_HTML_XSL}" "${TEST_DOC}" 

# the name attributes change
sed 's/name=\".*?\"//g' /tmp/docbook1.html > /tmp/docbook1.html
sed 's/name=\".*?\"//g' /tmp/docbook2.html > /tmp/docbook2.html

diff /tmp/docbook1.html /tmp/docbook2.html

if [[ $? -ne 0 ]]
then
	echo "************ xsltproc test 1 failed ************"
fi

# jing test 1
echo Starting jing test 1
echo '<!DOCTYPE article PUBLIC '-//OASIS//DTD DocBook XML V4.5//EN' 'http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd'>
<article><title>test</title><para>hi</para></article>' > "${TEMP_DOC}"
echo '<!DOCTYPE article PUBLIC '-//OASIS//DTD DocBook XML V4.5//EN' 'http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd'>
<article><title>test</title><para>hi</para></article>' > "${TEST_DOC}"
java -jar "${JING_JAR}" "${TEMP_DOC}" "${DOCBOOK_DTD}" > /tmp/jing1.tmp
java -jar "${JING_JAR}" "${TEST_DOC}" "${DOCBOOK_DTD}" > /tmp/jing2.tmp

diff /tmp/jing1.html /tmp/jing2.html

if [[ $? -ne 0 ]]
then
	echo "************ jing test 1 failed ************"
fi


# find test 1
#echo Starting find test 1. Grab a coffee, this will take a while.
#find /mnt/pressgang -name 3737.xml

#if [[ $? -ne 0 ]]
#then
#	echo "find test 1 failed"
#fi
